### ISSUE TITLE
params::realloc() appears to use undefined global

### ISSUE THREAD

**Issue by KerfuffleV2** [luapower/mysql#6]
```lua
function params:realloc(i, size)
	bind_check_range(self, i)
	assert(ffi.istype(data, 'uint8_t[?]'), 'attempt to realloc a fixed size field')
	local data = size > 0 and ffi.new('uint8_t[?]', size) or nil
```

Unless something magical is happening where a global `data` is set elsewhere, shouldn't that assert be using `self.data[i]` rather than `data`? Otherwise it seems like it's always just checking the type of `nil` against `uint8_t` which will never be true.

**Comment by capr** [comment]
I guess you're right. I haven't tested it but I made the modification. Thanks!

**Comment by KerfuffleV2** [comment]
No problem. I just found it randomly running a Lua linter which complained about the undefined global. I guess it never really caused an issue, possibly because the `realloc` method never actually gets called with fixed sized fields.

Should I just close the issue or were you waiting until you were able to test it?
